from tkinter import *
master = Tk()
master.title('registration')
master.geometry('500x500')
Label(master, text='First Name').grid(row=0)
Label(master, text='Last Name').grid(row=1)
e1 = Entry(master)
e2 = Entry(master)
e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
Label(master, text='Select sex').grid(row=2)
var1 = IntVar()
Checkbutton(master, text='male', variable=var1).grid(row=2, column=1, sticky=W)
var2 = IntVar()
Checkbutton(master, text='female', variable=var2).grid(row=3, column=1, sticky=W)
button = Button(master , text='Submit', width=25).grid(row =4)
mainloop()
